name: CD

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  cd:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows
            os: windows-latest
          - name: Linux
            os: ubuntu-latest
          - name: macOS (Intel)
            os: macos-13
          - name: macOS (ARM)
            os: macos-latest
    env:
      CSC_LINK: EVCertificate.pfx
      CSC_KEY_PASSWORD: ${{ secrets.EV_CERTIFICATE_PASSWORD }}
      EV_CERTIFICATE_BASE64: ${{ secrets.EV_CERTIFICATE_BASE64 }}
    steps:
      - name: Set the timezone to New Zealand
        uses: szenius/set-timezone@v2.0
        with:
          timezoneWindows: 'New Zealand Standard Time'
          timezoneLinux: 'Pacific/Auckland'
          timezoneMacos: 'Pacific/Auckland'
      - name: Check out OpenCOR
        uses: actions/checkout@v4
      - name: Retrieve the EV certificate (Windows only)
        if: matrix.name == 'Windows'
        shell: bash
        run: echo -n $EV_CERTIFICATE_BASE64 | base64 -d - > $CSC_LINK
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install Yarn
        run: npm install -g yarn
      - name: Packages OpenCOR
        run: |
          yarn
          yarn package
      - name: Remove blockmap files
        shell: bash
        run: find ./dist -name '*.blockmap' -delete
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: ./dist/OpenCOR-*.*
