name: CD

on:
  push:
    branches: [main]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  cd:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows
            os: windows-latest
          - name: Linux
            os: ubuntu-latest
          - name: macOS (Intel)
            os: macos-13
          - name: macOS (ARM)
            os: macos-latest
    steps:
      - name: Check out OpenCOR
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install Yarn
        run: npm install -g yarn
      - name: Packages OpenCOR
        run: |
          yarn
          yarn package
      - name: Remove blockmap files
        shell: bash
        run: find ./dist -name '*.blockmap' -delete
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: ./dist/OpenCOR-*.*
