name: CD (Development)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  web_app:
    if: ${{ github.repository == 'opencor/webapp' }}
    name: Web app
    runs-on: ubuntu-22.04
    steps:
      - name: Set the timezone to New Zealand
        run: sudo timedatectl set-timezone Pacific/Auckland
      - name: Check out OpenCOR
        uses: actions/checkout@v4
      - name: Install bun
        uses: oven-sh/setup-bun@v2
      - name: OpenCOR dependencies
        run: bun install
      - name: Build OpenCOR's Web app
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}
        run: bun build:web
      - name: Deploy to https://opencor.ws/appdev/
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: sftp
          remote-host: ${{ secrets.REMOTE_HOST }}
          remote-user: ${{ secrets.REMOTE_USER }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          local-path: ./src/renderer/dist
          remote-path: /home/www/opencor.ws/appdev
          sync: full
          # Note: our assets have a hash in their file names, so we upload index.html (which references them) once they
          #       have all been uploaded, so that it never references assets that are not available yet. Then, we upload
          #       version.json last so that OpenCOR's Web app only reports a new version once all the other files have
          #       been uploaded.
          ftp-mirror-options: --exclude-glob=index.html --exclude-glob=assets/version.json
          ftp-post-sync-commands: put -O /home/www/opencor.ws/appdev ./src/renderer/dist/index.html; put -O /home/www/opencor.ws/appdev/assets ./src/renderer/dist/assets/version.json
