name: CI

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows
            os: windows-latest
            script: win
          - name: Linux
            os: ubuntu-latest
            script: linux
          - name: macOS (Intel)
            os: macos-13
            script: mac
          - name: macOS (ARM)
            os: macos-latest
            script: mac
    steps:
      - name: Check out OpenCOR
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install all of OpenCOR's dependencies
        run: yarn
      - name: Check that OpenCOR's code and OpenCOR's Web app's code are properly formatted
        run: yarn format:check
      - name: Lint OpenCOR's code and OpenCOR's Web app's code
        run: yarn lint
      - name: Type check OpenCOR's code
        run: yarn typecheck
      - name: Type check OpenCOR's Web app's code
        run: yarn typecheck:web
      - name: Build OpenCOR
        run: yarn build
      - name: Build OpenCOR's Web app
        run: yarn build:web
      - name: Clean OpenCOR's environment
        run: yarn clean
