name: CI

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows (Intel)
            os: windows-2022
            build_script: build
          - name: Windows (ARM)
            os: windows-2019
            build_script: build:arm
          - name: Linux (Intel)
            os: ubuntu-22.04
            build_script: build
          - name: Linux (ARM)
            os: ubuntu-22.04-arm
            build_script: build
          - name: macOS (Intel)
            os: macos-13
            build_script: build
          - name: macOS (ARM)
            os: macos-14
            build_script: build
          - name: Code formatting
            os: ubuntu-22.04
          - name: Linting
            os: ubuntu-22.04
    steps:
      - name: Check out OpenCOR
        uses: actions/checkout@v4
      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: OpenCOR dependencies
        run: pnpm install
      - name: Build OpenCOR
        if: matrix.build_script != null
        run: pnpm ${{ matrix.build_script }}
      - name: Build OpenCOR's Web app
        if: matrix.build_script != null
        run: pnpm build:web
      - name: Code formatting
        if: matrix.name == 'Code formatting'
        run: pnpm format:check
      - name: Linting
        if: matrix.name == 'Linting'
        run: pnpm lint
      - name: Clean OpenCOR
        run: pnpm clean
