name: CI

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows (Intel)
            os: windows-2022
          #---OPENCOR--- The below is to be enabled once GitHub Actions has Windows ARM runners.
          # - name: Windows (ARM)
          #   os: windows-2022
          - name: Linux (Intel)
            os: ubuntu-22.04
          - name: Linux (ARM)
            os: ubuntu-22.04-arm
          - name: macOS (Intel)
            os: macos-13
          - name: macOS (ARM)
            os: macos-14
          - name: Code formatting
            os: ubuntu-22.04
          - name: Linting
            os: ubuntu-22.04
    steps:
      - name: Set the timezone to New Zealand
        uses: szenius/set-timezone@v2.0
        with:
          timezoneWindows: 'New Zealand Standard Time'
          timezoneLinux: 'Pacific/Auckland'
          timezoneMacos: 'Pacific/Auckland'
      - name: Check out OpenCOR
        uses: actions/checkout@v4
      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: OpenCOR dependencies
        run: pnpm install
      - name: Build libOpenCOR
        if: ${{ (matrix.name != 'Code formatting') && (matrix.name != 'Linting') }}
        run: pnpm libopencor
      - name: Build OpenCOR
        if: ${{ (matrix.name != 'Code formatting') && (matrix.name != 'Linting') }}
        run: pnpm build
      - name: Build OpenCOR's Web app
        if: ${{ (matrix.name != 'Code formatting') && (matrix.name != 'Linting') }}
        run: pnpm build:web
      - name: Code formatting
        if: matrix.name == 'Code formatting'
        run: pnpm format:check
      - name: Linting
        if: matrix.name == 'Linting'
        run: pnpm lint
      - name: Clean OpenCOR
        run: pnpm clean
