name: CI

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows
            os: windows-latest
            script: win
          - name: Linux
            os: ubuntu-latest
            script: linux
          - name: macOS (Intel)
            os: macos-13
            script: mac
          - name: macOS (ARM)
            os: macos-latest
            script: mac
    steps:
      - name: Check out OpenCOR
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install all of OpenCOR's dependencies
        run: pnpm install
      - name: Check that OpenCOR's code and OpenCOR's Web app's code are properly formatted
        run: pnpm format:check
      - name: Lint OpenCOR's code and OpenCOR's Web app's code
        run: pnpm lint
      - name: Type check OpenCOR's code
        run: pnpm typecheck
      - name: Type check OpenCOR's Web app's code
        run: pnpm typecheck:web
      - name: Build OpenCOR
        run: pnpm build
      - name: Build OpenCOR's Web app
        run: pnpm build:web
      - name: Clean OpenCOR's environment
        run: pnpm clean
